gredin_cantata_home:
    pattern:  /
    defaults: { _controller: GredinCantataBundle:Home:welcome }

gredin_cantata_signup:
    pattern: /signup
    defaults: { _controller: GredinCantataBundle:Registration:signup }
